export const SUCCESS_LOAD_VECTOR_MAP = 'SUCCESS_LOAD_VECTOR_MAP';
export const FAILURE_LOAD_VECTOR_MAP = 'FAILURE_LOAD_VECTOR_MAP';

export const SET_COLUMN = 'SET_COLUMN';
export const SET_ROW = 'SET_ROW';
