export const SUCCESS_LOAD_MAP = 'SUCCESS_LOAD_MAP';
export const FAILURE_LOAD_MAP = 'FAILURE_LOAD_MAP';

export const GET_CURRENT_LATITUDE = 'GET_CURRENT_LATITUDE';
export const GET_CURRENT_LONGITUDE = 'GET_CURRENT_LONGITUDE';

export const INCREMENT_ZOOM_LEVEL = 'INCREMENT_ZOOM_LEVEL';
export const DECREMENT_ZOOM_LEVEL = 'DECREMENT_ZOOM_LEVEL';

export const SET_NEW_LATITUDE = 'SET_NEW_LATITUDE';
export const SET_NEW_LONGITUDE = 'SET_NEW_LONGITUDE';
